### ISSUE TITLE
Move Cloud section above Docker in the roadmap

### ISSUE THREAD

**Issue by tarunclub** [WeMakeDevs/roadmaps#483]
### Description

Hello,

I would like to suggest moving the Cloud section above Docker in the roadmap.

In my opinion, cloud knowledge is essential before learning containerization in DevOps. As a beginner, I found it difficult to understand the concepts of Docker without prior knowledge of cloud technologies.

Therefore, I think it would be beneficial for beginners if the Cloud section is introduced before the Docker section in the roadmap. This would help in building a strong foundation before moving to more advanced concepts.

Thank you for considering my suggestion.

**Comment by siddhant-khisty** [comment]
I would sort of disagree with this point. The cloud is just another computer. It would be much more beneficial to understand containers on a local system first, before looking at them in a cloud environment. This provides much more understanding of how container work, since the backend processes are not getting abstracted.

**Comment by tarunclub** [comment]
@siddhant-khisty but in the saiyam pathak roadmap he told that learning cloud is necessary before containers
