### ISSUE TITLE
[LANGUAGE INDEPENDENT]

### ISSUE THREAD

**Issue by Tony-Stark-Jr** [WeMakeDevs/roadmaps#565]
### Description

<Some people have difficult to understand english language. So, can we provide best resources in different language.>

**Comment by RanaHuzaima** [comment]
Hey Bro,
Can you please assign me this issue? I can solve it very well.
Thanks,

**Comment by siddhant-khisty** [comment]
@Tony-Stark-Jr We are trying to keep this repo suitable for a global audience. Hence it would be best to keep the resources in English. At best, we could do something similar to what [90DaysOfDevOps](https://github.com/MichaelCade/90DaysOfDevOps/) does by adding multiple languages. However, I don't think that will be achievable for this repo, since we're pointing to other resources and not creating our own.

Feel free to open another issue if you have any ideas on how we can achieve this
